sudo: required
services:
  - docker

before_install:
  - docker build -t rajasekhar1996/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rajasekhar1996/react-test npm test

after_success:
  - docker build -t rajasekhar1996/multi-client ./client
  - docker build -t rajasekhar1996/multi-nginx ./nginx
  - docker build -t rajasekhar1996/multi-server ./server
  - docker build -t rajasekhar1996/multi-worker ./worker



