sudo: required
services:
  - docker

before_install:
  - docker build -t rajasekhar1996/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rajasekhar1996/react-test npm test

after_success:
  - docker build -t rajasekhar1996/multi-client ./client
  - docker build -t rajasekhar1996/multi-nginx ./nginx
  - docker build -t rajasekhar1996/multi-server ./server
  - docker build -t rajasekhar1996/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rajasekhar1996/multi-client
  - docker push rajasekhar1996/multi-nginx
  - docker push rajasekhar1996/multi-server
  - docker push rajasekhar1996/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: mult-docker
  env: mult-docker-env
  bucket_name: elasticbeanstalk-us-east-1-258531778277
  buket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY